import {IDataCatalogs} from "@/Interfaces/IDataCatalogs";

export const dataCatalogs: IDataCatalogs[] = [
    {
        id: 1,
        title: "Подвеска DOLCE & GABBANA",
        description: "Красивая подвеска!",
        type: "Подвески",
        price: 200000,
        brand: "DOLCE & GABBANA",
        gender: "Female",
        season: "Summer",
        event: "Holiday",
        img: "https://royal-time.ru/images/products/jNS2BDosLPCSRfr9Pe7t8w6G9RkNF0a5RjnJfvFG.jpg",
    },
    {
        id: 2,
        title: "Дизайнерское кольцо",
        description: "Красивое, дизайнерское кольцо!",
        type: "Кольца",
        price: 100000,
        brand: "Designer",
        gender: "Female",
        season: "Spring",
        event: "Holiday",
        img: "https://placepic.ru/wp-content/uploads/2018/08/6-2.jpg",
    },
    {
        id: 3,
        title: "Серебрянные серьги",
        description: "Серебряные серьги 925 пробы; родий черн.; вставки 28 Фианит корич.; 2 Цитрин; 26 Шпинель черн.;",
        type: "Серьги",
        price: 20000,
        brand: "Designer",
        gender: "Female",
        season: "Winter",
        event: "Marriage",
        img: "https://content.uvi.ru/upload/product/2078539/-1.jpg",
    },
    {
        id: 4,
        title: 'Запонки золотые "Весы"',
        description: "На этот раз мастера «Ювелирной коллекции» обратились к вечной и незыблемой классике – белое изображение на синем фоне! Встречайте запонки Весы. Серебряные весы представлены на фоне афганского лазурита. Белое на синем! \n" +
            "Материал: серебро\n" +
            "Варианты покрытия: родий\n" +
            "Вставка из камня: афганский лазурит\n" +
            "О серебре знают все, а вот про афганский лазурит следует рассказать. Поверьте, он этого заслуживает: недаром Плиний Старший писал, что этот минерал «подобен небесному своду, усеянному звездами». Лазурит известен  с глубокой древности, и был он одним из самых дорогих камней. Древние шумеры и египтяне именовали его \"камнем неба\".\n" +
            "Его любили правители всех эпох. Балдахин над троном иранского царя Хосрова II Парвиза (VI-VII века) был сделан из лазури и золота. Кроме того, по преданию, скрижали  Моисея были также сделаны из лазурита.",
        type: "Запонки",
        price: 15000,
        brand: "Designer",
        gender: "Male",
        season: "Autumn",
        event: "Holiday",
        img: "https://avatars.mds.yandex.net/get-mpic/5347250/img_id5525721217349680392.jpeg/orig",
    },
    {
        id: 5,
        title: 'Серебрянный браслет "Гранат"',
        description: "Серебряный браслет , полностью ручной работы .\n" +
            "Техника работы - филигрань .\n" +
            "Вставка - натуральный Гранат .\n" +
            "Авторский дизайн .\n" +
            "Возможно изготовление подобного браслета с учетом пожеланий заказчика ., а также с другими камнями .\n" +
            "Все вопросы к Мастеру .\n" +
            " © https://www.livemaster.ru/item/24867931-ukrasheniya-serebryanyj-braslet-granat",
        type: "Браслеты",
        price: 17800,
        brand: "Designer",
        gender: "Female",
        season: "Summer",
        event: "Holiday",
        img: "https://cs1.livemaster.ru/storage/b4/1c/7bdd7c6c798873d8b5af8763f0f7--ukrasheniya-serebryanyj-braslet-granat.jpg",
    },
    {
        id: 6,
        title: "Кварцевые часы",
        description: "Классические часы серии Eon отличаются сложностью. Циферблат дополняют хронографы и окошко даты, а рельефные отметки помогают считывать время. Минеральное стекло с сапфировым покрытием защищает циферблат. Японский кварцевый механизм дополнен мягким ремешком ручной работы из итальянской кожи.",
        type: "Часы",
        price: 15000,
        brand: "MIUZ",
        gender: "Female",
        season: "Spring",
        event: "Marriage",
        img: "https://static.insales-cdn.com/images/products/1/7748/542883396/1.jpg",
    },
    {
        id: 7,
        title: "Золотое кольцо",
        description: "Золотое кольцо 585 пробы; красное, белое золото; родий; вставки 26 Бр.Кр-57 0,195 4/5А; 1 Шпинель цв. лаванд. 1,39",
        type: "Кольца",
        price: 250000,
        brand: "ЭПЛ",
        gender: "Female",
        season: "Winter",
        event: "Marriage",
        img: "https://content.uvi.ru/upload/product/1057298/-1.jpg",
    },
    {
        id: 8,
        title: "Золотое кольцо",
        description: "Золотое кольцо 585 пробы; белое золото; родий; вставки 1 Бр.Кр-57 0,469 3/5А; 34 Бр.Кр-57 0,420 3/5А; 12 Бр.Кр-57 0,235 3/5А",
        type: "Кольца",
        price: 390000,
        brand: "АДАМАС",
        gender: "Female",
        season: "Autumn",
        event: "Marriage",
        img: "https://content.uvi.ru/upload/product/1058479/zolotoe-kolco-585-proby-1.jpg",
    },
    {
        id: 9,
        title: "Золотые серьги",
        description: "Золотые серьги 585 пробы; желтое золото; родий (бел.,черн.); вставки 134 Бр.Кр-57 0,615 3/5А; 20 Бр.Кр-57 0,139 3/6А; 8 Сапфир(H) св-роз. 0,051; 30 Са",
        type: "Серьги",
        price: 370000,
        brand: "SOKOLOV",
        gender: "Female",
        season: "Summer",
        event: "Marriage",
        img: "https://content.uvi.ru/upload/product/2072083/-1.jpg",
    },
    {
        id: 10,
        title: "Золотые серьги",
        description: "Золотые серьги 585 пробы; желтое золото; родий; вставки 112 Бр.Кр-57 1,443 3/6А; 2 Опал белый Эфиопия 4,29",
        type: "Серьги",
        price: 512000,
        brand: "AVGVST",
        gender: "Female",
        season: "Spring",
        event: "Holiday",
        img: "https://content.uvi.ru/upload/product/2072214/-1.jpg",
    },
    {
        id: 11,
        title: "Золотая подвеска",
        description: "Золотая подвеска 585 пробы; родий; вставки 2 Сапфир 0,009 2/2; 45 Бр.Кр-17 0,170 2/2А;",
        type: "Подвески",
        price: 35000,
        brand: "MIUZ",
        gender: "Female",
        season: "Winter",
        event: "Holiday",
        img: "https://content.uvi.ru/upload/product/500420/-1.jpg",
    },
    {
        id: 12,
        title: "Золотая подвеска",
        description: "Золотая подвеска 585 пробы; родий; вставки 16 Бр.Кр-57 0,515 4/5А; 1 Сапфир 1,22 2/2",
        type: "Подвески",
        price: 173000,
        brand: "ЭПЛ",
        gender: "Female",
        season: "Autumn",
        event: "Marriage",
        img: "https://content.uvi.ru/upload/product/059758/-1.jpg",
    },
    {
        id: 13,
        title: "Браслет из горного хрусталя с мантрой Прозрачный",
        description: "Браслет из горного хрусталя с мантрой Прозрачный\n" +
            "\n" +
            "Изготовлен из бусин обработанного горного хрусталя, собран на прочную двойную эластичную силиконовую резинку, хорошо зафиксирован, декорирован стойкой гипоаллергенной позолоченной фурнитурой класса люкс. Горный хрусталь проверен на натуральность. Очень стильно смотрится на руке!\n" +
            "\n" +
            "Красивая подарочная упаковка в комплекте.\n" +
            "\n" +
            "Этот браслет не просто красивый аксессуар, но ещë и очень полезная вещь.",
        type: "Браслеты",
        price: 1700,
        brand: "АДАМАС",
        gender: "Female",
        season: "Summer",
        event: "Holiday",
        img: "https://cs1.livemaster.ru/storage/04/c0/8409554489033680dd149358b9nf--ukrasheniya-braslet-iz-gornogo-hrustalya-s-mantroj-prozrachny.jpg",
    },
    {
        id: 14,
        title: "Браслет из лавы и серебра",
        description: "Двухрядный браслет в стиле шамбала из вулканической лавы и серебряных бусин (10шт) бесспорно станет эксклюзивным дополнением Вашего повседневного образа",
        type: "Браслеты",
        price: 29000,
        brand: "SOKOLOV",
        gender: "Male",
        season: "Spring",
        event: "Holiday",
        img: "https://cs5.livemaster.ru/storage/96/17/78e9464231faa38d2baa453390lw--ukrasheniya-braslet-iz-lavy-i-serebra-muzhskoj-braslet-iz-lav.jpg",
    },
    {
        id: 15,
        title: "Марказит часы",
        description: "Красивые женские часы!",
        type: "Часы",
        price: 28678,
        brand: "МАРКАЗИТ",
        gender: "Female",
        season: "Winter",
        event: "Marriage",
        img: "https://avatars.mds.yandex.net/get-goods_pic/5911219/picf1b7a99ce4d9be0e18305c17f24d01c4/orig",
    },
    {
        id: 16,
        title: "Наручные часы НИКА",
        description: "Красивые женские часы!",
        type: "Часы",
        price: 68500,
        brand: "MIUZ",
        gender: "Female",
        season: "Autumn",
        event: "Holiday",
        img: "https://avatars.mds.yandex.net/get-mpic/3707358/img_id1797344504994766570.jpeg/orig",
    },
]